version: '3.8'

services:
  umbraco:
    build: .
    container_name: umbraco-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__umbracoDbDSN=Data Source=/app/umbraco/Data/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True
      - ConnectionStrings__umbracoDbDSN_ProviderName=Microsoft.Data.Sqlite
      - Umbraco__CMS__Global__InstallMissingDatabase=true
      - Umbraco__CMS__Global__DatabaseServerMessenger__Enabled=false
      - Umbraco__CMS__Unattended__InstallUnattended=true
      - Umbraco__CMS__Unattended__UnattendedUserName=Admin
      - Umbraco__CMS__Unattended__UnattendedUserEmail=admin@example.com
      - Umbraco__CMS__Unattended__UnattendedUserPassword=AdminPassword123!
      - Umbraco__CMS__WebRouting__UmbracoApplicationUrl=https://your-domain.com
    volumes:
      - ./umbraco/media:/app/wwwroot/media
      - ./umbraco/logs:/app/umbraco/Logs
      - ./umbraco/data:/app/umbraco/Data
    networks:
      - umbraco-network

networks:
  umbraco-network:
    driver: bridge